#fixed values
FLASH="NA"
TYPE="NA"
BOARD="NA"
CUSTOMER="NA"
CAPLEVEL=0
LOGLVL=1
SECURITYLIST=("0" "1")
LOGLEVELLIST=("1" "2" "3" "4" "5")
CAPABILITYLIST=("1" "2" "3" "4" "5" "47104" "47360")
FLASHLIST=("2MB" "8MB" "4MB" "256KB")
BOARDLIST=("htap" "evb" "htap-mini" "he2-rev1" "he3")
CUSTOMERLIST=("AMBER_AC" "AMBER_AIRCOOLER" "HAVELLS_FAN" "HAVELLS_FAN" "HAVELLS_HANDTUNED" "HAVELLS_AC" "BAJAJFAN" "VIRTUALFOREST_AC" "VERSADEVICES_SUPERFAN" "VERSADEVICES_SUPERFAN_IOT" "POLYCAB_FAN" "HOAGS_DEMO_LIGHT" "HOAGS_DEMO_FAN" "LIVPURE_CHIMNEY" "UNISEMI" "RR_KABLES" "ATOMBERG_FAN" "VGUARD_NEW_FAN" "OMNI_AC" "INDCOOL_AC" "LIVPURE_PURIFIER" "CRUISE_AC")       
CHECKOUTPATH="/home/build/build-scripts"
CHECKOUTPARENTFOLDER="HE3"
SHA=NA

#github specific
GITUSER="Hema3041"
GITTOKEN="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"
GITHUBURL="https://$GITUSER:$GITTOKEN@github.com/Hema3041/Test"
GITBRANCH="main" 
GITSHA="NA""

#patch folder
PATCHPATH="$CHECKOUTPATH/patches/"

#flash specific
FLASHCFGPATH="Entry/HE1/RTL872xEA_v10.1c_beta/component/soc/amebalite/fwlib/usrcfg/"
FLASHLDPATH="Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/"
FLASHLDFILENAME="amebalite_layout.ld"
FLASHLDFILENAME2="amebalite_layout_2mb.ld"
FLASHLDFILENAME4="amebalite_layout_4mb.ld"
FLASHFILENAME="ameba_flashcfg.c"
FLASHFILENAME2="ameba_flashcfg_2mb.c"
FLASHFILENAME4="ameba_flashcfg_4mb.c"
FLASHCFG=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME
FLASHCFG2=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME2
FLASHCFG4=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME4
FLASHLD=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME
FLASHLD2=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME2
FLASHLD4=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME4

#versioning
MAKEFILE="sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/GCC-RELEASE/application.is.mk"
MANIFESTFILE="sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/GCC-RELEASE/amebaz2_firmware_is.json"
MANIFESTFILE_BOOTLOADER="sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/GCC-RELEASE/amebaz2_bootloader.json"
MANIFESTFILEPATH=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$MANIFESTFILE
MANIFESTFILEPATH_BOOTLOADER=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$MANIFESTFILE_BOOTLOADER
MAKEFILE_PATH=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$MAKEFILE
VERSION_HEADER_FILE="HE3/sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/inc/version.h"
MAJORDEV="0"
MAJORTEST="1"
MAJORPROD="2"

#security
SECURITYHAVELLSFOLDER="havells"
SECURITYVIRTUALFORESTFOLDER="virtualforest"
SECURITYVERSADEVICESFOLDER="versadevices"
SECURITYPOLYCABFOLDER="polycab"
SECURITYAMBERFOLDER="amber"
SECURITYLIVPUREFOLDER="livpure"
SECURITYPOCFOLDER="poc"
SECUREDPATH="./Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/project_km4/asdk/gnu_utility/image_tool/securityKeys/"
#SECUREDFILES=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$SECUREDPATH
#build
PLATFORM="he3"
DEVVERSIONFILE="devVersionHE3"
PRODVERSIONFILE="prodVersionHE3"
TESTVERSIONFILE="testVersionHE3"
VERSION="NA"
MAKEPATH="sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/GCC-RELEASE"
SRCIMAGEPATH="sdk-ameba-v7.1d/project/realtek_amebaz2_v0_example/GCC-RELEASE/application_is"
TARGETIMAGEPATH="/home/build/http-server/local/he3/"
BUILDLINK="http://192.168.0.109/builds/local/he3/"
BUILDNAME=NA
BODYFILE="mailBody"
SUBJFILE="mailSubject"
