#fixed values
FLASH="NA"
TYPE="NA"
BOARD="NA"
CUSTOMER="NA"
CAPLEVEL=0
LOGLVL=1
SECURITYLIST=("0" "1")
LOGLEVELLIST=("1" "2" "3" "4" "5")
CAPABILITYLIST=("1" "2" "3" "4")
FLASHLIST=("2" "4")
BOARDLIST=("htap" "evb" "htap-mini")
CUSTOMERLIST=("AMBER_AC" "AMBER_AIRCOOLER" "HAVELLS_FAN" "HAVELLS_FAN" "HAVELLS_AC" "BAJAJFAN" "VIRTUALFOREST_AC" "VERSADEVICES_SUPERFAN" "VERSADEVICES_SUPERFAN_IOT" "POLYCAB_FAN" "HOAGS_DEMO_LIGHT" "HOAGS_DEMO_FAN" "LIVPURE_CHIMNEY" "UNISEMI" "RR_KABLES" "ATOMBERG_FAN" "MOBILISE_FMHUB")
CHECKOUTPATH="/home/hoags/build-scripts"
CHECKOUTPARENTFOLDER="External"
SHA=NA

#github specific
GITUSER="hoagsgit"
GITTOKEN="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"
GITHUBURL="https://$GITUSER:$GITTOKEN@github.com/hoagstech/External"
GITBRANCH="main"
GITSHA="NA"

#patch folder
PATCHPATH="$CHECKOUTPATH/patches/"

#flash specific
FLASHCFGPATH="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/component/soc/amebalite/fwlib/usrcfg/"
FLASHLDPATH="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/"
FLASHLDFILENAME="amebalite_layout.ld"
FLASHLDFILENAME2="amebalite_layout_2mb.ld"
FLASHLDFILENAME4="amebalite_layout_4mb.ld"
FLASHFILENAME="ameba_flashcfg.c"
FLASHFILENAME2="ameba_flashcfg_2mb.c"
FLASHFILENAME4="ameba_flashcfg_4mb.c"
FLASHCFG=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME
FLASHCFG2=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME2
FLASHCFG4=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHCFGPATH/$FLASHFILENAME4
FLASHLD=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME
FLASHLD2=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME2
FLASHLD4=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$FLASHLDPATH/$FLASHLDFILENAME4

#versioning
MANIFESTFILE="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/project_km4/asdk/gnu_utility/image_tool/manifest_img2.json"
MANIFESTFILEPATH=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$MANIFESTFILE
MAJORDEV="0"
MAJORTEST="1"
MAJORPROD="2"

#security
SECURITYHAVELLSFOLDER="havells"
SECURITYVIRTUALFORESTFOLDER="virtualforest"
SECURITYVERSADEVICESFOLDER="versadevices"
SECURITYPOLYCABFOLDER="polycab"
SECURITYAMBERFOLDER="amber"
SECURITYLIVPUREFOLDER="livpure"
SECURITYPOCFOLDER="poc"
SECUREDPATH="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/project_km4/asdk/gnu_utility/image_tool/securityKeys/"
#SECUREDFILES=$CHECKOUTPATH/$CHECKOUTPARENTFOLDER/$SECUREDPATH
#build
PLATFORM="he1"
DEVVERSIONFILE="devVersion"
PRODVERSIONFILE="prodVersion"
TESTVERSIONFILE="testVersion"
VERSION="NA"
MAKEPATH="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/auto_build"
SRCIMAGEPATH="./FacilityManagement/Hub/Platform/Entry/HE1/RTL872xEA_v10.1c_beta/project/realtek_amebaLite_va0_example/GCC-RELEASE/project_km4/asdk/image"
TARGETIMAGEPATH="/home/hoags/http-server/local/he1/"
BUILDLINK="http://192.168.1.14/builds/local/he1/"
BUILDNAME=NA
BODYFILE="mailBody"
SUBJFILE="mailSubject"
